# Grab variables from the specific variable group
variables:
- group: 'Databricks-environment'

trigger:
  batch: true
  branches:
    exclude:
      - 'master'
    include:
      - '*'
  paths:
    exclude:
      - README.md
      - images
#  tags:
#    include:
#      - v*.*
#      - prod

pr:
  branches:
    include:
      - master
      - releases
  paths:
    exclude:
      - README.md
      - images
      
stages:
- stage: onPush
  condition: |
    and(
      ne(variables['Build.SourceBranch'], 'refs/heads/releases'),
      ne(variables['Build.SourceBranch'], 'refs/heads/master'),
      not(startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
    )
  jobs:
  - job: onPushJob
    pool:
      vmImage: 'ubuntu-18.04'

    steps:
    - script: env | sort
      displayName: 'Environment / Context'

    - task: UsePythonVersion@0
      displayName: 'Use Python 3.7'
      inputs:
        versionSpec: 3.7

    - checkout: self
      persistCredentials: true
      clean: true
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

    - script: |
        python -m pip install --upgrade pip nutter
      displayName: 'Install dependencies'

# https://docs.databricks.com/dev-tools/api/latest/repos.html
    - script: |
        set -x
        echo "Checking out the $(Build.SourceBranchName) branch"
        curl -s -n -X GET -o /tmp/staging-repo-info.json "$DATABRICKS_HOST/api/2.0/workspace/get-status" -H "Authorization: Bearer $DATABRICKS_TOKEN" -d '{"path":"/Repos/Staging/repos-automation"}'
        cat /tmp/staging-repo-info.json
        export STAGING_REPOS_ID=$(cat /tmp/staging-repo-info.json|grep '"object_type":"REPO"'|sed -e 's|^.*"object_id":\([0-9]*\).*$|\1|')
        curl -s -n -X PATCH -o "/tmp/$(Build.SourceBranchName)-out.json" "$DATABRICKS_HOST/api/2.0/repos/$STAGING_REPOS_ID" \
          -H "Authorization: Bearer $DATABRICKS_TOKEN" -d "{\"branch\": \"$(Build.SourceBranchName)\"}"
        cat "/tmp/$(Build.SourceBranchName)-out.json"
        grep -v error_code "/tmp/$(Build.SourceBranchName)-out.json"
      env:
        DATABRICKS_HOST: $(STAGING_DATABRICKS_HOST)
        DATABRICKS_TOKEN: $(STAGING_DATABRICKS_TOKEN)
      displayName: 'Update Staging project'

    - script: |
        nutter run '/Repos/Staging/repos-automation/' --cluster_id $(STAGING_CLUSTER_ID) --recursive --junit_report --timeout 500
      env:
        DATABRICKS_HOST: $(STAGING_DATABRICKS_HOST)
        DATABRICKS_TOKEN: $(STAGING_DATABRICKS_TOKEN)
      displayName: 'Execute Nutter tests'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test-*.xml' 
        failTaskOnFailedTests: true

- stage: onRelease
  condition: |
    or(
      eq(variables['Build.SourceBranch'], 'refs/heads/releases'),
      eq(variables['Build.SourceBranch'], 'refs/heads/master')
    )
  jobs:
  - job: onReleaseJob
    pool:
      vmImage: 'ubuntu-18.04'

    steps:
      - script: env | sort
        displayName: 'Environment / Context'

      - task: UsePythonVersion@0
        displayName: 'Use Python 3.7'
        inputs:
          versionSpec: 3.7

      - checkout: self
        persistCredentials: true
        clean: true
        displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

      - script: |
          set -x
          echo "Checking out the master branch"
          curl -s -n -X GET -o /tmp/prod-repo-info.json "$DATABRICKS_HOST/api/2.0/workspace/get-status" -H "Authorization: Bearer $DATABRICKS_TOKEN" -d '{"path":"/Repos/Production/repos-automation"}'
          cat /tmp/prod-repo-info.json
          export PRODUCTION_REPOS_ID=$(cat /tmp/prod-repo-info.json|grep '"object_type":"REPO"'|sed -e 's|^.*"object_id":\([0-9]*\).*$|\1|')
          curl -s -n -X PATCH -o "/tmp/master-out.json" "$DATABRICKS_HOST/api/2.0/repos/$PRODUCTION_REPOS_ID" \
            -H "Authorization: Bearer $DATABRICKS_TOKEN" -d "{\"branch\": \"master\"}"
          cat "/tmp/master-out.json"
          grep -v error_code "/tmp/master-out.json"
        env:
          DATABRICKS_HOST: $(PROD_DATABRICKS_HOST)
          DATABRICKS_TOKEN: $(PROD_DATABRICKS_TOKEN)
        displayName: 'Update Production repository'

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/test-*.xml' 
          failTaskOnFailedTests: true

